name: myFlutterApp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^1.0.0
  intl: any
  json_annotation: any
  http: 0.12.0+4
  retrofit: any
  logger: any
  dio: 2.2.2
  file_picker: any
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  progress_indicators: ^0.1.2
  dots_indicator: ^1.2.0
  get_it: ^5.0.6
  json_serializable: ^3.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  retrofit_generator: any

flutter:
  assets:
    - assets/images/
  uses-material-design: true

  fonts:
    - family: Schyler

